num = int(input('digite um número: '))
print(f'essa é a tabuada do número {num}:')
print(num*1) 
print(num*2) 
print(num*3) 
print(num*4) 
print(num*5)
print(num*6)
print(num*7)
print(num*8)
print(num*9)
print(num*10)